export enum ErrorCode {
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  NOT_PHASE_NOT_DRAW = 'NOT_PHASE_NOT_DRAW',
  NOT_YOUR_TURN = 'NOT_YOUR_TURN',
  CARD_NOT_IN_HAND = 'CARD_NOT_IN_HAND',
  INVALID_TARGET = 'INVALID_TARGET',
  OFFENSIVE_LIMIT_EXCEEDED = 'OFFENSIVE_LIMIT_EXCEEDED',
  TRAP_BLOCKS_OFFENSIVE = 'TRAP_BLOCKS_OFFENSIVE',
  TOO_MANY_ACTIONS = 'TOO_MANY_ACTIONS',
  ROOM_FULL = 'ROOM_FULL',
  INTERNAL = 'INTERNAL',
}
